// src/pages/Company.vue
<template>
    <Container id="content" class="company clearfix">
        <Row id="intro" padding-xs>
            <Col sm="6" padding-xs>
                <span class="heading-1">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec non velit nec velit mattis dictum vitae ut tellus. Maecenas dignissim sed lectus vitae auctor. Morbi laoreet posuere erat, nec finibus dolor tincidunt eget.</span>
            </Col>
            <Col sm="3" padding-xs></Col>
            <Col sm="3" class="aside" padding-xs>
                <section>
                    <b><span>Development</span> <span>&mdash;</span></b><br/>
                    <span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec non velit nec velit mattis dictum vitae ut tellus. Maecenas dignissim sed lectus vitae auctor. Morbi laoreet posuere erat, nec finibus dolor tincidunt eget.</span>
                </section>
                <section>
                    <b><span>Design</span> <span>&mdash;</span></b><br/>
                    <span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec non velit nec velit mattis dictum vitae ut tellus. Maecenas dignissim sed lectus vitae auctor. Morbi laoreet posuere erat, nec finibus dolor tincidunt eget.</span>
                </section>
                <section>
                    <b><span>Consultancy</span> <span>&mdash;</span></b><br/>
                    <span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec non velit nec velit mattis dictum vitae ut tellus. Maecenas dignissim sed lectus vitae auctor. Morbi laoreet posuere erat, nec finibus dolor tincidunt eget.</span>
                </section>
            </Col>
        </Row>
        <Row id="contact" padding-xs>
            <Col sm="6" padding-xs>
                <Address/>
                <br/>
                <div>
                    <a href="mailto:info@ovenwand.com">info@ovenwand.com</a><br/>
                    <br/>
                    KvK: 75344890<br/>
                    BTW: NL219654797B01<br/>
                    <br/>
                    <a href="https://www.linkedin.com/in/sibbe-heijne/" title="LinkedIn">
                        LinkedIn
                    </a><br/>
                    <a href="https://github.com/sheijne" title="Github">
                        Github
                    </a>
                </div>
            </Col>
        </Row>
    </Container>
</template>

<script>
import { Component, Mixins } from 'vue-property-decorator';
import Address from '../components/Address';
import Page from '../mixins/Page';

@Component({
  components: { Address },
  page: {
    title: 'Company',
    background: '/images/background.png',
  },
})
export default class Company extends Mixins(Page)
{
}
</script>

<style lang="scss">
    @import "../scss/mixins";

    .page-company {
        #content {
            margin-bottom: 80px;
            margin-top: 92px;

            @include screen-sm-and-up {
                margin-bottom: 120px;
                margin-top: 140px;
            }

            > .row#intro {
                @include screen-sm-and-up {
                    margin-bottom: 120px;
                }
            }

            > .row:not(:last-child) {
                @include screen-xs {
                    margin-bottom: 64px;
                }
            }

            .aside {
                margin-top: 80px;
                margin-bottom: 28px;
                text-align: right;

                section:not(:last-child) {
                    margin-bottom: 52px;
                }

                @include screen-md-and-up {
                    margin-top: 0;
                }
            }
        }
    }
</style>

// src/routes/company.svelte
<script>
    import { Address, UnderConstruction } from '@/components';
    import { Col, Container, Page, Row } from '@/core/components';
    import { action, fluid, BRAND } from '@/store/header';

    fluid.set(false);
    action.set(BRAND);
</script>

<style lang="scss">
    @import "../core/components/layout/mixins.scss";

    :global(.page-company) {
        :global(.aside) {
            @include screen-xs {
                margin-top: 6.4rem;
            }
        }

        :global(.aside section:not(:last-child)) {
            margin-bottom: 5.2rem;
        }
    }
</style>

<Page title="Company" background="/images/background.png" lightText>
    <Row relative paddingXs>
        <Col sm={6} paddingXs>
            <span class="display-1">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec non velit nec velit mattis dictum vitae ut tellus. Maecenas dignissim sed lectus vitae auctor. Morbi laoreet posuere erat, nec finibus dolor tincidunt eget.</span>
        </Col>

        <Col sm={3} paddingXs/>

        <Col class="aside" sm={3} paddingXs>
            <section id="development" class="text-align-right">
                <b><span>Development</span> <span>&mdash;</span></b>
                <br/>
                <span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec non velit nec velit mattis dictum vitae ut tellus. Maecenas dignissim sed lectus vitae auctor. Morbi laoreet posuere erat, nec finibus dolor tincidunt eget.</span>
            </section>

            <section id="design" class="text-align-right">
                <b><span>Design</span> <span>&mdash;</span></b>
                <br/>
                <span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec non velit nec velit mattis dictum vitae ut tellus. Maecenas dignissim sed lectus vitae auctor. Morbi laoreet posuere erat, nec finibus dolor tincidunt eget.</span>
            </section>

            <section id="consultancy" class="text-align-right">
                <b><span>Consultancy</span> <span>&mdash;</span></b>
                <br/>
                <span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec non velit nec velit mattis dictum vitae ut tellus. Maecenas dignissim sed lectus vitae auctor. Morbi laoreet posuere erat, nec finibus dolor tincidunt eget.</span>
            </section>
        </Col>

        <UnderConstruction/>
    </Row>

    <Row paddingXs>
        <Col sm={6} paddingXs>
            <Address/>
            ETC
        </Col>
    </Row>
</Page>
