// src/components/Footer.vue
<template>
    <div class="footer">
        <span>&copy; {{ brand }} {{ year }}</span>
    </div>
</template>

<script>
import { Component, Vue } from 'vue-property-decorator';

@Component
export default class Footer extends Vue
{
  brand = 'Ovenwand';

  get year() {
    return 2019;
  }
}
</script>

<style lang="scss">
    .footer {
        bottom: 0;
        left: 0;
        padding: 12px;
        position: absolute;
        right: 0;
        text-align: center;

        span {
            font-size: 20px;
            transition: color .2s ease;
        }
    }
</style>

// src/components/Footer.svelte
<script>
    import { name } from '@/store/brand';

    const currentYear = (new Date()).getFullYear();
</script>

<style lang="scss">
    footer {
        padding: 1.2rem;
        pointer-events: none;

    span {
            font-size: 2rem;
            transition: color .2s ease;
            pointer-events: all;
        }
    }
</style>

<footer id="app-footer" class="text-align-center">
    <span>&copy; {$name} {currentYear}</span>
</footer>
